SELECT CAR_ID, CC.CAR_TYPE, (DAILY_FEE*(100-DISCOUNT_RATE)*0.01*30) FEE
FROM CAR_RENTAL_COMPANY_CAR CC INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE CC.CAR_TYPE IN ('세단', 'SUV')
    AND DURATION_TYPE LIKE '30%'
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND (DAILY_FEE*(100-DISCOUNT_RATE)*0.01*30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;