SELECT SCORE, HE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE INNER JOIN (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) HG
ON HE.EMP_NO = HG.EMP_NO
ORDER BY SCORE DESC LIMIT 1;