SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM (
    SELECT IFNULL(LENGTH, 10) LENGTH, FISH_TYPE
    FROM FISH_INFO
) SUB_FISH
GROUP BY FISH_TYPE 
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;