SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO RI INNER JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) RR
ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;