SELECT SUM(COUNT) FISH_COUNT
FROM FISH_NAME_INFO FNI INNER JOIN (
    SELECT FISH_TYPE, COUNT(*) COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) FI 
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');

