SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SUM_SALES) TOTAL_SALES
FROM BOOK B JOIN (
    SELECT BOOK_ID, SUM(SALES) SUM_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) BS ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID  = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;