SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE UF JOIN (
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD 
    ORDER BY VIEWS DESC LIMIT 1
) UGB
ON UF.BOARD_ID = UGB.BOARD_ID
ORDER BY FILE_PATH DESC;