SELECT HRD.DEPT_ID, HRD.DEPT_NAME_EN, AST.AVG_SAL
FROM HR_DEPARTMENT HRD INNER JOIN (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AVG_SAL
    FROM HR_EMPLOYEES 
    GROUP BY DEPT_ID
) AST
WHERE HRD.DEPT_ID = AST.DEPT_ID
ORDER BY AST.AVG_SAL DESC;