SELECT B.CATEGORY CATEGORY, SUM(S.SUM_SALES) TOTAL_SALES
FROM BOOK B JOIN (
    SELECT BOOK_ID, SUM(SALES) SUM_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;