SELECT RI.FOOD_TYPE, REST_ID, REST_NAME, RI.FAVORITES
FROM REST_INFO RI INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) MF
ON RI.FOOD_TYPE = MF.FOOD_TYPE
WHERE RI.FAVORITES = MF.FAVORITES
ORDER BY RI.FOOD_TYPE DESC;