SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO FNI INNER JOIN FISH_INFO FI
ON FNI.FISH_TYPE = FI.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) FML
ON FML.FISH_TYPE = FI.FISH_TYPE
WHERE LENGTH = MAX_LEN
ORDER BY ID;