SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER U INNER JOIN (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM (
        SELECT *
        FROM USED_GOODS_BOARD
        WHERE STATUS = 'DONE'
    ) DONE_LIST
    GROUP BY WRITER_ID
) TOTAL_LIST
ON USER_ID = WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;